title: "Mickey Vellukunnel"
description: "Thoughts, notes, and experiments by Mickey Vellukunnel."
author: "Mickey Vellukunnel"
url: "" # Set to 'https://username.github.io' after deployment
baseurl: "" # Leave empty for root

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Mickey Vellukunnel"

theme: null

exclude:
  - README.md

